name: Deploy Joomla to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install unzip
      run: sudo apt-get update && sudo apt-get install unzip -y

    - name: Install Composer
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php --filename=composer --install-dir=/usr/local/bin
        php -r "unlink('composer-setup.php');"

    - name: Set Composer defaults
      run: |
        echo "{\"name\":\"joomla/joomla\",\"description\":\"Joomla CMS\",\"authors\":[{\"name\":\"kishore1278\",\"email\":\"yuvadonadi17@gmail.com\"}],\"minimum-stability\":\"stable\"}" > composer.json

    
    - name: Download Joomla
      run: |
        wget https://github.com/joomla/joomla-cms/archive/refs/tags/4.3.0.zip
        unzip 4.3.0.zip

    - name: Push to My Git Remote Repository
      run: |
        git config --global user.email "yuvadonadi17@gmail.com"
        git config --global user.name "kishore1278"
        git add .
        git commit -m "Add Joomla files version 4.3.0"
        git push https://$GH_TOKEN@github.com/kishore1278/joomla_version.git main
      env:
        GH_TOKEN: ${{secrets.GH_TOKEN}}

